baseURL = 'https://the-pauper-cube.pages.dev'
languageCode = 'en-us'
title = 'The Pauper Cube - Draft Guide & Reference'
theme = 'hugo-book'

# Book theme configuration
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = 'auto'
  
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true
  
  # (Optional, default none) Set leaf bundle to render as side menu
  BookMenuBundle = '/menu'
  
  # (Optional, default docs) Specify section of content to render as menu
  BookSection = 'docs'
  
  # (Optional) Set to 'true' to hide 'Git Repository' button on top right of page.
  BookRepo = 'https://github.com/dunamismax/the-pauper-cube'
  
  # (Optional) Set to 'commit' to fetch git commit info for page
  BookGitInfo = 'commit'
  
  # (Optional) Set to 'true' to enable search
  BookSearch = true
  
  # (Optional) Set to 'true' to enable comments
  BookComments = false
  
  # (Optional) Set to menu position where to render this menu item
  BookPortableLinks = true
  
  # (Optional) Set to 'false' to disable mobile menu toggle
  BookMenuToggle = true

# Enable custom CSS
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

# Configure menus
[menu]
  [[menu.before]]
    name = "The Pauper Cube"
    url = "/"
    weight = 10
  
  [[menu.after]]
    name = "Cube Cobra List"
    url = "https://cubecobra.com/cube/list/thepaupercube"
    weight = 10
    
  [[menu.after]]
    name = "Official Site"
    url = "https://thepaupercube.com/"
    weight = 20
    
  [[menu.after]]
    name = "Discord"
    url = "https://discord.gg/Px2JhHM"
    weight = 30

# SEO and social
[params.seo]
  description = "The ultimate draft guide and reference for The Pauper Cube - a curated Magic: The Gathering pauper format cube designed for the perfect drafting experience."
  keywords = ["magic the gathering", "pauper", "cube", "draft", "mtg", "common cards", "limited"]
  
[params.social]
  discord = "https://discord.gg/Px2JhHM"
